import { NextRequest, NextResponse } from "next/server"
import crypto from "crypto"

export async function POST(req: NextRequest) {
  try {
    // Read request body
    const { secret, userId, merchantId, amount } = await req.json()

    if (!secret || !userId || !merchantId || !amount) {
      return NextResponse.json(
        { error: "Missing payment parameters" },
        { status: 400 }
      )
    }

    // Step 1 - Generate cryptographic properties from secret
    const commitment = crypto.createHash("sha256").update(secret).digest("hex")
    
    // In ZK, the nullifier prevents double-spends. For the hackathon,
    // we derive a unique nullifier from the secret + merchantId + timestamp
    const nullifierStr = secret + merchantId + Date.now().toString()
    const nullifier = "0x" + crypto.createHash("sha256").update(nullifierStr).digest("hex").substring(0, 60)

    // Step 2 - Call the new Express backend running on 4000
    const backendPayload = {
      proof: { mock: true, note: "Generated by frontend proxy for hackathon demo" },
      publicSignals: [String(amount), nullifier, commitment],
      fromUserId: userId,
      toAddress: merchantId,
      amount: Number(amount)
    }

    // Generate mock signature headers for authentication middleware
    const timestamp = Date.now().toString()
    const signature = "mock_signature_for_" + userId

    const res = await fetch("http://localhost:4000/api/payment/submit", {
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-user-id": userId,
        "x-timestamp": timestamp,
        "x-signature": signature
      },
      body: JSON.stringify(backendPayload),
      cache: "no-store" 
    })

    const data = await res.json()

    if (!res.ok) {
      return NextResponse.json(
        { error: data.message || data.error || "Payment failed at backend" },
        { status: res.status }
      )
    }

    // Return success response to the client
    return NextResponse.json({
      success: true,
      message: "Payment successful",
      txId: data.transactionId,
      amount: amount
    })

  } catch (error: any) {
    console.error("Payment Error:", error)
    return NextResponse.json(
      { error: error.message || "Payment processing failed" },
      { status: 500 }
    )
  }
}